name: Daily Task Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *" # Runs daily at 5:40 AM IST

permissions:
  contents: write # Grant write access to the repository

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # Install dependencies
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # Run the script to update files and send email update
      - name: Run Name Update Script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: ruby main_script.rb

      # Add and commit changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add .
          git status
          git commit -m "Daily update to files on $(date +'%Y-%m-%d')" || echo "No changes to commit"

      # Push changes
      - name: Push changes
        run: |
          git push origin main
